# app/bot/sender.py
"""
It generates and sends Telegram messages and dynamic prompts.

Behavior implemented:
- Uses TELEGRAM_BOT_TOKEN from Settings without exposing it.
- Runs blocking HTTP calls in a thread to avoid blocking the event loop.
- Provides: generate_dynamic_prompt, send_typing, send_message, send_progressive, send_start_keyboard.
- Graceful error handling and defensive input validation.
"""
import json
import traceback
from typing import Any, Dict, Optional

import requests
from anyio.to_thread import run_sync

from app.core.config import Settings
from app.agents.agent_loop import client 

settings = Settings()
BASE_URL = f"https://api.telegram.org/bot{settings.TELEGRAM_BOT_TOKEN}"


async def _post(url: str, payload: Dict[str, Any]) -> None:
    """
    Helper: perform a requests.post in a thread to avoid blocking.
    """
    def _send() -> None:
        try:
            requests.post(url, json=payload, timeout=10)
        except Exception:
            traceback.print_exc()

    await run_sync(_send)


async def generate_dynamic_prompt(user_text: str, context: str, chat_id: Optional[int] = None) -> str:
    """
    It generates a short, friendly message in the same language as the user.

    - Uses the shared agent client to request a short prompt.
    - Returns a safe fallback message if the LLM call fails.
    """
    if not isinstance(user_text, str):
        user_text = ""

    prompt = f"""
The user wrote: "{user_text}"

Generate a short, friendly message in the SAME LANGUAGE as the user.
Context: {context}

Rules:
- One sentence.
- Natural language.
- No emojis unless context allows.
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=50,
        )
        try:
            content = response.choices[0].message.content
        except Exception:
            content = None
        if isinstance(content, str) and content.strip():
            return content.strip()
    except Exception:
        traceback.print_exc()

    return "Please choose a stock."


def send_typing(chat_id: int) -> None:
    """
    Sends the 'typing' chat action. Best-effort, non-blocking for caller.
    """
    if not chat_id:
        return
    url = f"{BASE_URL}/sendChatAction"
    payload = {"chat_id": chat_id, "action": "typing"}

    try:
        requests.post(url, json=payload, timeout=5)
    except Exception:
        traceback.print_exc()


def send_message(chat_id: int, text: str, reply_markup: Optional[Dict[str, Any]] = None) -> None:
    """
    Sends a simple message to a chat.

    - reply_markup must be a dict; it will be JSON-serialized.
    - parse_mode defaults to Markdown.
    """
    if not chat_id or text is None:
        return

    url = f"{BASE_URL}/sendMessage"
    payload: Dict[str, Any] = {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "Markdown",
    }

    if reply_markup:
        payload["reply_markup"] = json.dumps(reply_markup)

    try:
        requests.post(url, json=payload, timeout=10)
    except Exception:
        traceback.print_exc()


async def send_progressive(chat_id: int, text: str, chunk_size: int = 500, delay: float = 0.6) -> None:
    """
    Sends a long message in chunks with typing indicator between chunks.

    - chunk_size controls the size of each chunk.
    - delay controls the pause between chunks.
    """
    if not chat_id or not text:
        return


    chunks = [text[i:i + chunk_size] for i in range(0, len(text), chunk_size)]

    for chunk in chunks:
        try:
            send_typing(chat_id)
        except Exception:
            pass
        
        try:
            import asyncio as _asyncio
            await _asyncio.sleep(delay)
        except Exception:
            pass
        try:
            send_message(chat_id, chunk)
        except Exception:
            traceback.print_exc()


async def send_start_keyboard(chat_id: int, user_text: str) -> None:
    """
    Sends a dynamic message generated by the LLM plus a stock selection keyboard.

    - Uses generate_dynamic_prompt for the message.
    - Sends the keyboard as inline buttons.
    """
    if not chat_id:
        return

    try:
        msg = await generate_dynamic_prompt(user_text or "", context="ask user to choose a stock", chat_id=chat_id)
    except Exception:
        traceback.print_exc()
        msg = "Please select a stock:"

    keyboard = {
        "inline_keyboard": [
            [{"text": "TSLA", "callback_data": "symbol:TSLA"}],
            [{"text": "AAPL", "callback_data": "symbol:AAPL"}],
            [{"text": "MSFT", "callback_data": "symbol:MSFT"}],
        ]
    }

    try:
        await _post(f"{BASE_URL}/sendMessage", {"chat_id": chat_id, "text": msg, "reply_markup": json.dumps(keyboard)})
    except Exception:
        traceback.print_exc()
        try:
            send_message(chat_id, msg)
        except Exception:
            pass
